{
 "title": "Parity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ethereum Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_block_number" }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(eth_block_number[10m])" }
   ]
  },
  {
   "title": "Ethereum Latest Block Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_latest_block_transactions" }
   ]
  },
  {
   "title": "Gas Price (in gwei)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "gwei" }
   ],
   "targets": [
    { "expr": "eth_gas_price / 1000000000" }
   ]
  },
  {
   "title": "Active Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "parity_net_active_peers" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "parity_net_connected_peers" }
   ]
  }
 ]
}